### ISSUE TITLE
Twemoji updated

### ISSUE THREAD

**Issue by alextes** [ZxMYS/react-twemoji#36]
Some emojis aren't rendering on our site, I'm guessing because Twemoji updated recently and the new emojis are only in the latest twemoji version somehow.

red envelope and mate are two examples.

**Comment by ZxMYS** [comment]
Hi, are you using the latest version of react-twemoji?

**Comment by alextes** [comment]
Yea guess not, something on my side anyway. CodeSandbox looks fine 👍 .

https://codesandbox.io/s/bitter-voice-r8m9ew?file=/src/App.js
