### ISSUE TITLE
How to use other sizes?

### ISSUE THREAD

**Issue by Brianzchen** [ZxMYS/react-twemoji#37]
What sizes are available to pass into the `size` property inside `options`? Anything else I pass besides 72 gives me an error and will render default emoji's instead.

If I can't up the size it tends to get blurry if I make the emoji very large. Any tips?

**Comment by ZxMYS** [comment]
This is a more a question for twemoji itself and you can ask in its github repo https://github.com/twitter/twemoji.
but in general, if you need very large twemoji images you should use svg instead (i.e. setting `folder` and `ext`). You can look at the twemoji document for an example.

**Comment by Brianzchen** [comment]
Thanks! Awesome answer ☺️
