### ISSUE TITLE
Twemoji image urls throw ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by 8spw** [ZxMYS/react-twemoji#47]
I'm using Next.js 14 and I've installed react-twemoji, I simply pass text prop where emojis are included

```js
import Twemoji from "react-twemoji";

<Twemoji>
    <p className="text-sm mt-1">{message}</p>
</Twemoji>
```

It renders default system emojis in browser instead of twemoji, I checked console and seeing it throws network error when trying to fetch twemoji images
<img width="820" alt="image" src="https://github.com/user-attachments/assets/1d71afd6-8199-42da-be29-9c2404fb923b">
https://twemoji.maxcdn.com/v/14.0.1/72x72/1f62d.png
here is url

**Comment by anriuss** [comment]
yeah same for me

**Comment by ZxMYS** [comment]
https://github.com/twitter/twemoji/issues/580
