### ISSUE TITLE
prevent wrapping div

### ISSUE THREAD

**Issue by timohausmann** [ZxMYS/react-twemoji#6]
Hi, great module, thanks!

It would be awesome though if you could prevent the [wrapping div](https://github.com/ZxMYS/react-twemoji/blob/master/src/Twemoji/index.js#L31) since it can cause issues with existing layouts and css. 

Maybe it could be replaced with [React.Fragment](https://reactjs.org/docs/fragments.html) or sth?

**Comment by ZxMYS** [comment]
Thanks. This is a very reasonable request. I will add it soon.
To keep things backward compatible though I'd add it as a boolean flag maybe.

**Comment by ZxMYS** [comment]
Commit d51f97cbb2ba2422b1caa4283fcbc7444350068c closes this.
