### ISSUE TITLE
Having `noWrapper={true}` attribute throws error!

### ISSUE THREAD

**Issue by rehman-00001** [ZxMYS/react-twemoji#8]
Hi,
I receive this error whenever I set this flag `noWrapper`.

```
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `Twemoji`.
```

Could you please verify once?
Thanks!

**Comment by ZxMYS** [comment]
Hi. It's likely that your React version is too old. Try updating it to 16.4.x.

**Comment by rehman-00001** [comment]
Thanks for the immediate response! I just created a new react project to try this library.
`create-react-app` version: 2.1.3
`react` version: 16.8.6

is 16.4.x is the preferred react version?

**Comment by ZxMYS** [comment]
no, anything equal to or newer than 16.4.x should work.

**Comment by ZxMYS** [comment]
I see, it's because you are using noWrapper without your own wrapper of text. Added some code to take care of this case and print a better error message in 0.2.1.
